name: MCP Quix Streaming Reader
language: python
variables:
  - name: QUIX_TOKEN
    inputType: Secret
    multiline: false
    defaultValue: API_PAT
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
