name: MCP Quix Streaming Reader
language: python
variables:
  - name: QUIX_TOKEN
    inputType: Secret
    multiline: false
    defaultValue: API_PAT
    required: true
  - name: QUIX_WORKSPACE
    inputType: FreeText
    multiline: false
    defaultValue: demo-webinarsolarfarm-btestv1
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
